# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'im_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 7, 1, 1, 1)
        self.connectedUserListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.connectedUserListWidget.setMaximumSize(QtCore.QSize(140, 16777215))
        self.connectedUserListWidget.setObjectName("connectedUserListWidget")
        self.gridLayout.addWidget(self.connectedUserListWidget, 6, 4, 1, 1, QtCore.Qt.AlignRight)
        self.cmdEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cmdEdit.setObjectName("cmdEdit")
        self.gridLayout.addWidget(self.cmdEdit, 7, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.chatAreaEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.chatAreaEdit.setObjectName("chatAreaEdit")
        self.gridLayout.addWidget(self.chatAreaEdit, 6, 0, 1, 4)
        self.endChatButton = QtWidgets.QPushButton(self.centralwidget)
        self.endChatButton.setObjectName("endChatButton")
        self.gridLayout.addWidget(self.endChatButton, 7, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.me_label = QtWidgets.QLabel(self.centralwidget)
        self.me_label.setObjectName("me_label")
        self.gridLayout_4.addWidget(self.me_label, 1, 1, 1, 1)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setObjectName("status_label")
        self.gridLayout_4.addWidget(self.status_label, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 5, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.server_status_label = QtWidgets.QLabel(self.centralwidget)
        self.server_status_label.setObjectName("server_status_label")
        self.gridLayout_5.addWidget(self.server_status_label, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 5, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.endChatButton.setText(_translate("MainWindow", "End Chat"))
        self.label_2.setText(_translate("MainWindow", "Current User:"))
        self.label_3.setText(_translate("MainWindow", "Current Chat:"))
        self.me_label.setText(_translate("MainWindow", "me"))
        self.status_label.setText(_translate("MainWindow", "none, find someone to talk to"))
        self.server_status_label.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Connected Users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
